package it.polimi.ingsw.client.controller.exceptions;

/**
 * This object represents a generic command exception generated by the cli
 * @author Daniele Ferrario
 */
public abstract class CliCommandException extends Exception{
    public CliCommandException(String message) {
        super(message);
    }
}
